In [1]:
import pandas as pd

In [14]:
edit_df = pd.read_json('../results/edit_requests/all_edit_requests.jsonl', lines=True)

In [15]:
edit_df = edit_df.explode("editRequests").reset_index(drop=True)

In [16]:
edit_df

,slug,editRequests,totalCount,hasMore,fetched_at
0,Barrington_High_School_(Illinois),"{'supportingEvidence': [], 'id': 'd1d20be0-d1e...",2,False,2025-11-14 20:23:14.572297
1,Barrington_High_School_(Illinois),"{'supportingEvidence': [], 'id': '49d754bc-c26...",2,False,2025-11-14 20:23:14.572297
2,Barry_Windham,"{'supportingEvidence': [], 'id': 'b3e9a4e0-a61...",1,False,2025-11-14 20:26:15.053542
3,Bart_De_Wever,"{'supportingEvidence': [], 'id': 'd470d6c7-56b...",1,False,2025-11-14 20:26:45.259247
4,Al_Hurricane,"{'supportingEvidence': [], 'id': '450f3452-ac9...",4,False,2025-11-14 22:16:21.147461
...,...,...,...,...,...
11271,Lê_Thánh_Tông,"{'supportingEvidence': [], 'id': 'cc31ef48-a63...",1,False,2025-11-14 23:50:48.935830
11272,Lüderitz,"{'supportingEvidence': [], 'id': '1dc35007-46f...",1,False,2025-11-14 23:51:18.566606
11273,Lüneburg,"{'supportingEvidence': [], 'id': 'a02288bb-70f...",1,False,2025-11-14 23:51:18.566617
11274,M._K._Stalin,"{'supportingEvidence': [], 'id': 'f7317910-e55...",2,False,2025-11-14 23:54:19.926050
11275,M._K._Stalin,"{'supportingEvidence': [], 'id': 'e042c817-ee0...",2,False,2025-11-14 23:54:19.926050

In [17]:
edit_df = pd.json_normalize(edit_df["editRequests"])

In [19]:
edit_df.groupby('slug').count().sort_values('id', ascending=False)[:50]

,supportingEvidence,id,userId,status,type,summary,originalContent,proposedContent,sectionTitle,createdAt,updatedAt,reviewedBy,reviewedAt,reviewReason,upvoteCount,downvoteCount,userVote,editStartHeader,editEndHeader
slug,,,,,,,,,,,,,,,,,,,
Elon_Musk,196,196,196,196,196,196,196,196,196,196,196,196,196,196,196,196,196,196,196
The_Church_of_Jesus_Christ_of_Latter-day_Saints,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77
Starlink,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75
Russian_invasion_of_Ukraine,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74
SpaceX_Starship,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68
George_Floyd,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62
Donald_Trump,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60
Inflation_Reduction_Act,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53
Franz_Schubert,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49
Israel,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48
Impossible_Foods,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45
Stardew_Valley,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44
SpaceX_Starship_integrated_flight_test_1,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44,44
Adolf_Hitler,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
Jesus,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39
Ilham_Aliyev,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37
Transgender,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
Wikipedia,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
Charlie_Kirk,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33
Solana_(blockchain_platform),33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33
Mark_Meechan,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
Eunice_Newton_Foote,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
Mathias_Gidsel,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31
X_Corp.,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31
Islam,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31
Anna_Paulina_Luna,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
Gamergate,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
Kiwi_Farms,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
Greenhouse_effect,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29
Bhagwanji,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28
Ukraine,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27
January_6_United_States_Capitol_attack,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
Grok_(chatbot),26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
Gender,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
European_Train_Control_System,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
SpaceX,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Bridget_(Guilty_Gear),25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Jimmy_Carr,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
Bitcoin,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
Great_Barrington_Declaration,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
Bitcoin.com,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
Climate_change,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
1984_anti-Sikh_riots,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23
Jill_Valentine,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
2022_Tour_de_France,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
AFD,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
Bellamy_salute,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
The_Holocaust,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
Mormons,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
Bitcoin_Cash,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20

In [23]:
edit_df.userId.value_counts()[:50]

userId
518f378c-afe5-489f-b5d8-5052631b4f76    142
68c2f0a6-8720-4b30-b387-4a079fc227ef     74
6b05a628-a4c1-4971-852b-4a395dd29627     72
aa7f98a3-e4e3-493f-b56c-2011b35fe41c     59
60901d50-6ca5-41f9-b085-3fa764abc5d3     54
f68b0285-d40f-4825-8507-4792676f7892     53
fd968b45-0923-4aad-824c-2050cbb08688     49
cd95f6d9-ebcf-4446-8cfd-5202e28fd7e8     45
c1d89be2-7b71-4ce3-90af-a20a981637de     44
a78924b8-e17c-44f0-9a92-ce8aecc2482e     44
8fde1c54-b223-4cbc-b38a-c5a72525fc8d     41
6bcdf34c-615b-4589-b6c4-d72c5bc53a30     41
3b556a2a-3b98-420a-b3fe-f2bfa4948041     40
ec420b82-30c9-423e-8287-03a80e9faa2d     39
09e6ef4c-03c9-4daa-8ca1-25dea758462e     37
f89ea28e-2c14-41aa-9298-2b8cdd889217     36
54d05765-5ce6-48a5-be03-e9e9cbd99e36     33
ecc396b9-cae6-4348-a3ab-2e63985dca7e     33
d419a235-5d60-48ae-a20a-716326da6d13     32
c378120f-d133-4b7a-b8ec-0efb5030aa00     30
235e5c6a-d3e6-4b75-b2a9-79ddccf3cceb     30
f19c8487-7189-4720-a633-571f43070bdf     29
1bb21f40-1d46-4d5a-b9cf-206cf41bc748     29
cbea6c9f-40ab-4ab8-8e53-66983ee1b0a4     28
f8fbebc6-b1a9-4243-bea7-d0d6f65c5343     25
e430cd16-1567-4806-8067-4bfed27af722     25
8fa26df8-dbb5-4713-b906-3751964ce7f4     25
b83d61bf-31ca-4a9d-9e31-4b07f0c5f5d6     24
3f4cdd35-3215-4a00-bf46-5180cedf0058     24
8d396df7-2bf5-496c-8d68-e790b11a6bc5     23
13e1f0cb-88a7-44b6-8fe9-3e4f93f71e90     21
7a698af2-2f4a-4685-ab0e-360da4e8bbfc     21
36881e05-e39c-4918-94fe-3259223fa1e0     21
860b50b0-c8f2-453f-a3b4-e98dbf66b8f7     21
a0c5b3d4-59d3-4db8-9522-25cbbb1acdeb     20
7c63db10-5e82-4606-8cf5-a194e045fbc5     20
a31270fd-ba60-4d98-8257-f21fd40aeb56     20
2eb3edd0-0eb0-4917-aa3a-3975228ac575     20
62abb801-6768-400e-90be-7e02bff71435     20
c86c41e6-ed95-4fb0-bf6c-733de198c1e3     19
8ecaddb3-05e0-4461-9604-6625fc8792a8     19
5d3bf434-9f14-4cca-b422-6a5bfdabfcd0     19
90c873c2-f96c-4559-8b02-ad7001dc3f4a     18
869ba295-422b-444c-906d-3881afb4a180     18
4f54f9c8-1f27-48a1-b8a3-1821aba4742f     18
b7ae77ea-ebbd-4e06-8f15-9d947b377856     18
f49d7d72-1f2c-45bc-8f8e-ca27e3b653b2     18
2beb6265-3411-40be-8942-5c18e999c18f     17
e808f6a3-515b-4af3-8b38-6cd8e841fe7d     17
7a9f7da6-311f-4a66-9443-7de94c8669b2     17
Name: count, dtype: int64

In [48]:
edit_df[edit_df.userId == '518f378c-afe5-489f-b5d8-5052631b4f76'].groupby('slug').count().sort_values('id', ascending=False)[:50]

,supportingEvidence,id,userId,status,type,summary,originalContent,proposedContent,sectionTitle,createdAt,updatedAt,reviewedBy,reviewedAt,reviewReason,upvoteCount,downvoteCount,userVote,editStartHeader,editEndHeader
slug,,,,,,,,,,,,,,,,,,,
Starlink,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
Mathias_Gidsel,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31
X_Corp.,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28
SpaceX,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
Niklas_Landin_Jacobsen,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
THW_Kiel,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Simon_Pytlick,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Forsen,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

In [26]:
edit_df[edit_df.userId == '68c2f0a6-8720-4b30-b387-4a079fc227ef'].groupby('slug').count().sort_values('id', ascending=False)[:50]

,supportingEvidence,id,userId,status,type,summary,originalContent,proposedContent,sectionTitle,createdAt,updatedAt,reviewedBy,reviewedAt,reviewReason,upvoteCount,downvoteCount,userVote,editStartHeader,editEndHeader
slug,,,,,,,,,,,,,,,,,,,
Nations_and_IQ,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Physical_attractiveness,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Face_perception,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Hair_loss,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Intelligence,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Occupational_prestige,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Evolutionary_psychology,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Corruption,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Social_psychology,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Total_fertility_rate,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
United_States,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Piaget's_theory_of_cognitive_development,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
IQ_and_Global_Inequality,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Cross-cultural_psychology,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
IQ_and_the_Wealth_of_Nations,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Color_psychology,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Human_Development_Index,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Gross_domestic_product,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Education,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Climate_change,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Corruption_Perceptions_Index,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Cross-cultural_studies,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Differential_psychology,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Donald_Trump,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Social_Progress_Index,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Richard_Lynn,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Pattern_hair_loss,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Social_inequality,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Sociology,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Social_status,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Status,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Waist–hip_ratio,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [27]:
edit_df[edit_df.userId == '6b05a628-a4c1-4971-852b-4a395dd29627'].groupby('slug').count().sort_values('id', ascending=False)[:50]

,supportingEvidence,id,userId,status,type,summary,originalContent,proposedContent,sectionTitle,createdAt,updatedAt,reviewedBy,reviewedAt,reviewReason,upvoteCount,downvoteCount,userVote,editStartHeader,editEndHeader
slug,,,,,,,,,,,,,,,,,,,
Israel,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Dragon_Ball_GT,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Christianity,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Green_Party_(UK),3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Islam,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Book_of_Enoch,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Shroud_of_Turin,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Sonic_Superstars,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Criticism_of_Islam,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Conservative_Party_(UK),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Discord,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Great_Replacement_theory,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Cornwall,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Christian_Whitehead,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Catholic_Church,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Grok_(chatbot),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Green_Party_of_England_and_Wales,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Dragon_Ball_Z,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Judaism,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Michelle_Obama,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Musk_family,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Labour_Party_(UK),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Martin_Luther_King_Jr.,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Reform_UK,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Nigel_Farage,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
State_of_Palestine,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
The_Book_of_Giants,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
UK_Independence_Party,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Ukraine,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Wikipedia,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Zack_Polanski,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [35]:
edit_df[
    (edit_df.userId == '6b05a628-a4c1-4971-852b-4a395dd29627') &
    (edit_df.status.isin(['EDIT_REQUEST_STATUS_APPROVED', 'EDIT_REQUEST_STATUS_IMPLEMENTED']))
][['slug', 'sectionTitle']]

                     slug                             sectionTitle
4886         Christianity   Defining Characteristics as a Religion
4887         Christianity   Defining Characteristics as a Religion
4889         Christianity                             Christianity
4890         Christianity                             Christianity
4891         Christianity                             Christianity
4892         Christianity                             Christianity
4893         Christianity                             Christianity
5363        Book_of_Enoch                            Book of Enoch
8124   Criticism_of_Islam
10141              Israel  21st-Century Conflicts and Developments
10142              Israel                                   Israel
10143              Israel                                   Israel
10144              Israel                                   Israel
10145              Israel                                   Israel
10148              Israel                                   Israel
10149              Israel                                   Israel
10150              Israel                                   Israel
10151              Israel                                   Israel
10153              Israel                                   Israel

In [37]:
edit_df[
    (edit_df.userId == '6b05a628-a4c1-4971-852b-4a395dd29627') &
    (edit_df.status.isin(['EDIT_REQUEST_STATUS_APPROVED', 'EDIT_REQUEST_STATUS_IMPLEMENTED'])) &
    (edit_df.slug == 'Israel')
]

,supportingEvidence,id,slug,userId,status,type,summary,originalContent,proposedContent,sectionTitle,createdAt,updatedAt,reviewedBy,reviewedAt,reviewReason,upvoteCount,downvoteCount,userVote,editStartHeader,editEndHeader
10141,[],c1c24664-e46e-4578-bba1-0d2990e24129,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,Update the figure,"50,000 reported Palestinian deaths by April 2025",,21st-Century Conflicts and Developments,1763164214,1763164252,ai-pipeline,1763164252,The edit suggestion aims to update the reporte...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,21st-Century Conflicts and Developments,Geography and Environment
10142,[],56583acb-39ec-4f57-8edb-0cd646d9d10c,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"Israel existed long before that, it existed in...",Israel was founded on 14 May 1948 through the ...,,Israel,1763164001,1763164032,ai-pipeline,1763164032,The edit suggestion seeks to add historical co...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Israel,History
10143,[],fde78c74-5881-4c26-9d5e-272b1181cb19,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"Wrong brackets, use () instead of []",[established under a British mandate from the ...,,Israel,1763163684,1763163699,ai-pipeline,1763163699,The edit suggestion proposes changing square b...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Israel,History
10144,[],01f7d600-51f0-4da7-bbce-71cbc81e6821,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"You don't need a new sentence for Palestine, s...",partition of Mandatory Palestine into Jewish a...,,Israel,1763163558,1763163578,ai-pipeline,1763163578,The edit suggestion focuses on restructuring s...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Israel,History
10145,[],af2466c5-77aa-4496-9747-05ba59c7b428,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,This doesn't read well and could be more factu...,Founded on 14 May 1948 through the Declaration...,,Israel,1763163418,1763163441,ai-pipeline,1763163441,The edit suggestion focuses on improving reada...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Israel,History
10148,[],ad64806a-37d4-448e-ad3f-8a47efc6ee34,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,Might want to add that mandatory Palestine cam...,Mandatory Palestine into Jewish and Arab states,,Israel,1763163123,1763163148,ai-pipeline,1763163148,Researched the origin of Mandatory Palestine u...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Israel,History
10149,[],be145c8f-129c-4df8-b9b3-c6edc9003564,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"Not just their refuge, their homeland too",Israel emerged as a refuge,,Israel,1763163017,1763163062,ai-pipeline,1763163062,The edit suggestion seeks to expand the phrase...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Israel,History
10150,[],b4b50a51-90af-4b9a-aced-aaabdfb0b5bf,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,Known to jews/israel as Judea and Samaria,the West Bank and Gaza Strip,,Israel,1763162714,1763162738,ai-pipeline,1763162738,Web searches confirmed that the Israeli govern...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Israel,History
10151,[],5e336daf-bf7b-40ad-a9cd-64e1a8e3ba34,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"This paragraph doesn't read well, refractor it",Israel is a sovereign parliamentary democracy ...,,Israel,1763162647,1763162669,ai-pipeline,1763162669,The edit suggestion proposes refactoring the h...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Israel,History
10153,[],6fc5805b-f586-4479-8b87-567f53cd98c3,Israel,6b05a628-a4c1-4971-852b-4a395dd29627,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,Also update that it is the birthplace of Chris...,as the nation-state of the Jewish people.[1][2],,Israel,1763162454,1763162493,ai-pipeline,1763162493,Researched the geographical origins of Christi...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Israel,History

In [30]:
edit_df[edit_df.userId == 'aa7f98a3-e4e3-493f-b56c-2011b35fe41c'].groupby(['slug', 'status']).count().sort_values('id', ascending=False)[:50]

                                                     supportingEvidence  id  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED                  18  18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED                  15  15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED                     14  14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED                     10  10
                    EDIT_REQUEST_STATUS_APPROVED                      2   2

                                                     userId  type  summary  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED      18    18       18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED      15    15       15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED         14    14       14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED         10    10       10
                    EDIT_REQUEST_STATUS_APPROVED          2     2        2

                                                     originalContent  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED               18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED               15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED                  14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED                  10
                    EDIT_REQUEST_STATUS_APPROVED                   2

                                                     proposedContent  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED               18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED               15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED                  14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED                  10
                    EDIT_REQUEST_STATUS_APPROVED                   2

                                                     sectionTitle  createdAt  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED            18         18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED            15         15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED               14         14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED               10         10
                    EDIT_REQUEST_STATUS_APPROVED                2          2

                                                     updatedAt  reviewedBy  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED         18          18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED         15          15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED            14          14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED            10          10
                    EDIT_REQUEST_STATUS_APPROVED             2           2

                                                     reviewedAt  reviewReason  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED          18            18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED          15            15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED             14            14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED             10            10
                    EDIT_REQUEST_STATUS_APPROVED              2             2

                                                     upvoteCount  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED           18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED           15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED              14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED              10
                    EDIT_REQUEST_STATUS_APPROVED               2

                                                     downvoteCount  userVote  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED             18        18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED             15        15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED                14        14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED                10        10
                    EDIT_REQUEST_STATUS_APPROVED                 2         2

                                                     editStartHeader  \
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED               18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED               15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED                  14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED                  10
                    EDIT_REQUEST_STATUS_APPROVED                   2

                                                     editEndHeader
slug                status
Eunice_Newton_Foote EDIT_REQUEST_STATUS_IMPLEMENTED             18
Greenhouse_effect   EDIT_REQUEST_STATUS_IMPLEMENTED             15
Eunice_Newton_Foote EDIT_REQUEST_STATUS_REJECTED                14
Greenhouse_effect   EDIT_REQUEST_STATUS_REJECTED                10
                    EDIT_REQUEST_STATUS_APPROVED                 2

In [31]:
edit_df[edit_df.userId == 'aa7f98a3-e4e3-493f-b56c-2011b35fe41c']

,supportingEvidence,id,slug,userId,status,type,summary,originalContent,proposedContent,sectionTitle,createdAt,updatedAt,reviewedBy,reviewedAt,reviewReason,upvoteCount,downvoteCount,userVote,editStartHeader,editEndHeader
3307,[],7313e4fd-6707-49b2-84b8-cb167251f5df,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"patent 45,148 or 45,149? or both"" eralier in t...",Foote secured multiple U.S. patents for practi...,,Published Works and Archival Record,1763154558,1763154587,ai-pipeline,1763154587,Researched Eunice Newton Foote's patents via w...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Published Works and Archival Record,References
3308,[],c1d07cb5-30be-4782-8532-b5b4e22475af,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,propose sentence removal as experiment is deta...,This paper examined static electricity generat...,,Published Works and Archival Record,1763154483,1763154496,ai-pipeline,1763154496,The edit proposes removing a sentence summariz...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Published Works and Archival Record,References
3309,[],9eea1c60-c4a6-4fee-8808-ffdccdc2f8df,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose removing this sentence, as the experim...",This four-page article described experiments u...,,Published Works and Archival Record,1763154468,1763154481,ai-pipeline,1763154481,The edit suggestion proposes removing a descri...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Published Works and Archival Record,References
3310,[{'url': 'https://grokipedia.com/page/Eunice_N...,be6e7b1a-769e-4072-ae85-d31491821515,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,this is duplicate of earlier in the article. s...,Published Works and Archival Record\nEunice Ne...,,Published Works and Archival Record,1763154251,1763154286,ai-pipeline,1763154286,Browsed the full article at the provided URL t...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Published Works and Archival Record,References
3311,[],0496fffb-aba8-42d7-b121-028ab1100015,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,propose removing this entire section as a dupl...,Published Works and Archival Record\nEunice Ne...,,Published Works and Archival Record,1763153991,1763154002,ai-pipeline,1763154002,The edit suggestion proposes removing the enti...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Published Works and Archival Record,References
3312,[],4c18f11d-99c7-45ca-b324-1979d91abb36,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose ""Such framings, common in media and ad...","Such framings, common in media and advocacy co...",,Modern Recognition and Critiques of Narrative ...,1763153920,1763153953,ai-pipeline,1763153953,"The edit proposes changing ""Tyndall's causal e...",0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Modern Recognition and Critiques of Narrative ...,Published Works and Archival Record
3313,[],c28013bb-165d-414e-8a93-89e5935f14d0,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose ""rendering Foote's role inspirational ...",rendering Foote's role inspirational rather th...,,Modern Recognition and Critiques of Narrative ...,1763153793,1763153813,ai-pipeline,1763153813,The edit suggestion proposes rephrasing the hi...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Modern Recognition and Critiques of Narrative ...,Published Works and Archival Record
3314,[{'url': 'https://ramanathan.ucsd.edu/wp-conte...,b3d8257d-b20a-4a14-bf5b-46d427512687,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose "" highlighting her early empirical obs...",highlighting her early empirical observation o...,,Modern Recognition and Critiques of Narrative ...,1763153617,1763153651,ai-pipeline,1763153651,"The edit proposes replacing ""heat-trapping pro...",0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Modern Recognition and Critiques of Narrative ...,Published Works and Archival Record
3315,[],f4fa559c-b5a1-4454-9e33-6c42250aef21,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose change 2nd sentence to: ""This omission...","However, the experiments primarily demonstrate...",,Evaluations of Experimental Validity,1763153486,1763153532,ai-pipeline,1763153532,"The edit proposes removing ""quantitatively"" fr...",0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Evaluations of Experimental Validity,Debates on Priority and Influence Over Tyndall
3316,[{'url': 'https://ramanathan.ucsd.edu/wp-conte...,b23070a4-eee2-4f57-99ea-38e901f75a82,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"the 2nd paragraph contains ""Recent research sh...","However, the experiments primarily demonstrate...",,Evaluations of Experimental Validity,1763153211,1763153251,ai-pipeline,1763153251,"Researched claims using web searches on ""incre...",0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Evaluations of Experimental Validity,Debates on Priority and Influence Over Tyndall
3317,[],527b5309-898f-457c-8892-274d5f264e2c,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose shortening and edit to: ""This omission...",This omission meant Foote's work did not quant...,,Evaluations of Experimental Validity,1763152892,1763152924,ai-pipeline,1763152924,The edit suggestion proposes rewriting the hig...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Evaluations of Experimental Validity,Debates on Priority and Influence Over Tyndall
3318,[{'url': 'https://ramanathan.ucsd.edu/wp-conte...,fe4e82b6-b85c-4c4e-912f-6d3ac587ce8d,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose: ""Foote's approach, employing a simple...","Foote's approach, employing a simple paired-tu...",,Evaluations of Experimental Validity,1763152497,1763152549,ai-pipeline,1763152549,The edit proposes rewriting the final paragrap...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Evaluations of Experimental Validity,Debates on Priority and Influence Over Tyndall
3319,[{'url': 'https://ramanathan.ucsd.edu/wp-conte...,d0743534-e093-4e0f-8b99-f423b2c8e7bb,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose shortening to: ""This omission meant Fo...",This omission meant Foote's work did not quant...,,Evaluations of Experimental Validity,1763152425,1763152499,ai-pipeline,1763152499,The edit proposes rewriting the highlighted te...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Evaluations of Experimental Validity,Debates on Priority and Influence Over Tyndall
3320,[],ef30e6b7-284e-4fa8-86ae-6a1a1213ae3d,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose: ""Foote's approach, employing a simple...","Foote's approach, employing a simple paired-tu...",,Evaluations of Experimental Validity,1763152225,1763152249,ai-pipeline,1763152249,The edit proposes rewriting the concluding par...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Evaluations of Experimental Validity,Debates on Priority and Influence Over Tyndall
3321,[],a02bda1d-5684-4466-9126-44cd925ef821,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose shortening to: ""This omission meant Fo...",This omission meant Foote's work did not quant...,,Evaluations of Experimental Validity,1763151947,1763151964,ai-pipeline,1763151964,The edit proposes rewriting the highlighted te...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Evaluations of Experimental Validity,Debates on Priority and Influence Over Tyndall
3322,[],10490032-133c-4a44-b899-22d50231aeb5,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose ""This obscurity persisted into the 20t...",This obscurity persisted into the 20th century...,,Historical Obscurity and 2011 Rediscovery,1763151759,1763151779,ai-pipeline,1763151779,The edit suggestion proposes shortening the se...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Historical Obscurity and 2011 Rediscovery,Evaluations of Experimental Validity
3323,[],7b9037ff-7594-4006-8a11-f165a71b487c,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose ""No records indicate Foote sought acad...",No records indicate Foote sought academic affi...,,Post-Scientific Activities,1763151549,1763151567,ai-pipeline,1763151567,"Web searches for ""Eunice Newton Foote reasons ...",0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Post-Scientific Activities,Circumstances of Death
3324,[],cb96f766-5243-41fa-a524-5b9a5af11733,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"proposed: ""Tyndall's subsequent refinements, i...","Tyndall's subsequent refinements, including di...",,Comparisons with John Tyndall and Other Contem...,1763151254,1763151284,ai-pipeline,1763151284,The edit proposes adding a clarifying phrase t...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Comparisons with John Tyndall and Other Contem...,Later Years and Death
3325,[],c1f981fd-ce44-4184-90ab-e7c1499a387d,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"""Tyndall's subsequent refinements, including d...","Tyndall's subsequent refinements, including di...",,Comparisons with John Tyndall and Other Contem...,1763144173,1763144212,ai-pipeline,1763144212,The edit suggestion seeks to revise the conclu...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Comparisons with John Tyndall and Other Contem...,Later Years and Death
3326,[],85dad244-350d-421d-8780-d194ad180624,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"proposal: ""Foote's inference that elevated atm...",Foote's inference that elevated atmospheric ca...,,Limitations in Scope and Precision,1763144022,1763144068,ai-pipeline,1763144068,The edit is a rewrite of the highlighted parag...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Limitations in Scope and Precision,Comparisons with John Tyndall and Other Contem...
3327,[],6fb67863-e85a-4ae1-9f56-0af6b99abad7,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"suggest removing ""and establishing a qualitati...",This marked the earliest documented experiment...,,Methodological Strengths and Empirical Findings,1763143590,1763143619,ai-pipeline,1763143619,The edit suggestion proposes removing the phra...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Methodological Strengths and Empirical Findings,Limitations in Scope and Precision
3328,[],76794446-258c-46b0-b199-8aba8a932a3e,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"This sentence is a bit confused, suggest remov...",These results aligned with foundational physic...,,Methodological Strengths and Empirical Findings,1763143495,1763143534,ai-pipeline,1763143534,The edit suggestion proposes removing the sent...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Methodological Strengths and Empirical Findings,Limitations in Scope and Precision
3329,[],ec71aef0-0bac-4209-902f-fb3b19a93071,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"propose ""Foote concluded that carbonic acid ga...",Foote concluded that carbonic acid gas absorbs...,,Experimental Setup and 1856 Solar Heat Experim...,1763143281,1763143315,ai-pipeline,1763143315,The edit proposes rewriting the description of...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Experimental Setup and 1856 Solar Heat Experim...,1857 Electrical Excitation Research
3330,[],ac531bdf-a360-436d-b4ad-ebcc2755cea8,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"Propose: ""Foote's most notable scientific cont...",Foote's most notable scientific contribution c...,,Eunice Newton Foote,1763142973,1763143002,ai-pipeline,1763143002,The edit is a targeted rewrite of a single par...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Eunice Newton Foote,Early Life and Background
3331,[],d92a4721-c5f4-43fc-b1b6-28a244496a65,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"Re: ""This empirical demonstration established ...",Foote's most notable scientific contribution c...,,,1763141702,1763141738,ai-pipeline,1763141738,The edit suggestion proposes rewording a key s...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,,
3332,[{'url': 'https://ramanathan.ucsd.edu/wp-conte...,4b523e54-29c7-4c97-9d6d-80094439925f,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"Proposed added context for accuracy: ""This emp...",This empirical demonstration established her a...,,Eunice Newton Foote,1763140619,1763140667,ai-pipeline,1763140667,The edit suggestion proposes adding a clause t...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Eunice Newton Foote,Early Life and Background
3333,[{'url': 'https://ramanathan.ucsd.edu/wp-conte...,ef6d274b-b316-4ce7-854b-1e9d8aceb2a0,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,peer-reviewed research indicates greater absor...,This empirical demonstration established her a...,,Eunice Newton Foote,1763140163,1763140193,ai-pipeline,1763140193,The edit suggestion attempts to reframe Foote'...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Eunice Newton Foote,Early Life and Background
3334,[],024ef2ed-d0e3-4828-ad9c-91f6a8115549,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"""This empirical demonstration established her ...","This empirical demonstration, which preceded s...",,Eunice Newton Foote,1763139272,1763139291,ai-pipeline,1763139291,"The edit proposes removing the clause ""which p...",0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Eunice Newton Foote,Early Life and Background
3335,[{'url': 'https://grokipedia.com/page/Greenhou...,173aef28-9d14-489a-aa44-1a8f7b8983cd,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"as already stated in the article, Foote showed...","This empirical demonstration, which preceded s...",,,1763138852,1763138875,ai-pipeline,1763138875,Researched Eunice Foote's experiment and histo...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,,
3336,[{'url': 'https://grokipedia.com/page/Greenhou...,9c3c3d47-4850-4eb6-a06d-a2514fef25b7,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"Propose: ""Foote's most notable scientific cont...",Foote's most notable scientific contribution c...,,Eunice Newton Foote,1763138109,1763138157,ai-pipeline,1763138157,The edit suggestion proposes rephrasing the de...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Eunice Newton Foote,Early Life and Background
3337,[{'url': 'https://grokipedia.com/page/Greenhou...,5fc3c567-9af9-4df6-8c19-2d3380497d13,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"Propose: ""Foote's most notable scientific cont...",Foote's most notable scientific contribution c...,,Eunice Newton Foote,1763137586,1763137631,ai-pipeline,1763137631,Researched Eunice Foote's experiment using web...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Eunice Newton Foote,Early Life and Background
3338,[{'url': 'https://grokipedia.com/page/Greenhou...,870d8c48-6532-4710-a28e-f5ae11a9e74c,Eunice_Newton_Foote,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"For accuracy and neutrality, suggest: ""Foote c...",Foote's most notable scientific contribution c...,,Eunice Newton Foote,1763136809,1763136854,ai-pipeline,1763136854,The edit suggestion proposes rewriting the des...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Eunice Newton Foote,Early Life and Background
9262,[],0fcd9859-14a2-449d-b9e7-cd49cd756f8e,Greenhouse_effect,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"""could influence"" --> ""could increase"". Foote ...",concluding that this gas's greater heat retent...,,Early Observations and Hypotheses,1763203578,1763203606,ai-pipeline,1763203606,Web searches for Eunice Newton Foote's 1856 ex...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Early Observations and Hypotheses,20th-Century Confirmation and Refinements
9263,[],ac182011-24bb-4dfa-abba-6c9bc8f63e1f,Greenhouse_effect,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,The atmosphere is largely heated by convection...,The greenhouse effect operates through the sel...,,Basic Physical Principles,1763157305,1763157364,ai-pipeline,1763157364,"Researched using web searches on ""primary heat...",0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Basic Physical Principles,Historical Development
9264,[],9a078575-8ac6-4c23-a80a-5c4480e70ba3,Greenhouse_effect,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,"awkward paragraph, starts by talking of absorp...",The greenhouse effect is the infrared radiativ...,,Definition,1763157235,1763157264,ai-pipeline,1763157264,The edit suggestion identifies a potential iss...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Definition,Basic Physical Principles
9265,[],79c71a26-105a-4448-9322-fbb8e68b333a,Greenhouse_effect,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,The atmosphere is largely heated by convection...,Greenhouse gases comprise a small fraction of ...,,Greenhouse Gases,1763157027,1763157065,ai-pipeline,1763157065,The edit suggestion proposes adding nuance to ...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Greenhouse Gases,Primary Gases: Water Vapor and Carbon Dioxide
9266,[],959bccf1-4e1f-4e48-bbf0-7f28fc2325f9,Greenhouse_effect,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_REJECTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,The atmosphere is largely heated by convection...,The process maintains thermal equilibrium as t...,,Basic Physical Principles,1763157006,1763157032,ai-pipeline,1763157032,The edit suggestion proposes adding content to...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Basic Physical Principles,Historical Development
9267,[],51e8e5db-d4bd-4c43-899f-639a130be556,Greenhouse_effect,aa7f98a3-e4e3-493f-b56c-2011b35fe41c,EDIT_REQUEST_STATUS_IMPLEMENTED,EDIT_REQUEST_TYPE_UPDATE_INFORMATION,The atmosphere is largely heated by convection...,Definition\nThe greenhouse effect is the infra...,,Definition,1763156981,1763157010,ai-pipeline,1763157010,The edit suggestion proposes adding clarificat...,0,0,EDIT_REQUEST_VOTE_TYPE_UNSPECIFIED,Definition,Basic Physical Principles

In [43]:
edit_df[
    (edit_df.status.isin(['EDIT_REQUEST_STATUS_APPROVED', 'EDIT_REQUEST_STATUS_IMPLEMENTED']))
][['slug', 'sectionTitle', 'id']].groupby(['slug', 'sectionTitle']).count().sort_values('id', ascending=False)[:50]

                                                                                          id
slug                                            sectionTitle
The_Church_of_Jesus_Christ_of_Latter-day_Saints                                           59
Elon_Musk                                                                                 58
SpaceX_Starship                                                                           40
Stardew_Valley                                                                            31
SpaceX_Starship_integrated_flight_test_1                                                  28
Charlie_Kirk                                                                              22
Mark_Meechan                                                                              18
Russian_invasion_of_Ukraine                                                               17
Anna_Paulina_Luna                                                                         17
Great_Barrington_Declaration                                                              16
Kiwi_Farms                                                                                16
George_Floyd                                                                              16
Bitcoin.com                                                                               15
Randall_Franks                                                                            14
Shock_collar                                                                              13
Bitcoin_Cash                                                                              13
Impossible_Foods                                Operational Challenges and Restructuring  13
Infant_Annihilator                                                                        12
Atari_2600                                                                                12
Solana_(blockchain_platform)                                                              12
Leclerc                                                                                   12
European_Train_Control_System                                                             12
Asmongold                                                                                 11
Larry_Sanger                                                                              11
Bhagwanji                                                                                 11
Xiao_Zhan                                                                                 11
West_Bromwich_Albion_F.C.                                                                 10
Grok_(chatbot)                                                                            10
Prunella_Scales                                                                           10
Inflation_Reduction_Act                                                                    9
Donald_Trump                                                                               9
Discovery_Institute                                                                        9
Bridget_(Guilty_Gear)                                                                      9
Jared_Isaacman                                                                             9
Gad_Saad                                                                                   9
Israel                                          Israel                                     9
Danny_Masterson                                                                            8
Protestant_Church_in_Germany                                                               8
Ayn_Rand                                                                                   8
Bitcoin                                                                                    8
2025_Formula_One_World_Championship                                                        8
SpaceX_Starship_integrated_flight_test_2                                                   8
Chia_(cryptocurrency)                                                                      8
Starship_Troopers                                                                          8
Bettina_Arndt                                                                              8
Gender                                                                                     8
Gamergate                                                                                  8
Liberal_Initiative                                                                         8
Jez_San                                                                                    8
Jefferson–Hemings_controversy                                                              7

In [47]:
with pd.option_context('display.max_colwidth', None):
    display(
        edit_df[
            (edit_df.status.isin(['EDIT_REQUEST_STATUS_APPROVED', 'EDIT_REQUEST_STATUS_IMPLEMENTED'])) &
            (edit_df.slug == 'Israel')
        ][['summary', 'originalContent', 'reviewReason']]
    )

,summary,originalContent,reviewReason
10141,Update the figure,"50,000 reported Palestinian deaths by April 2025","The edit suggestion aims to update the reported Palestinian death toll figure from ""over 50,000 by April 2025"" to reflect more recent data, as the current date is November 14, 2025. Research via web searches for ""Gaza war Palestinian death toll as of November 2025"" and ""latest Gaza health ministry death toll November 2025"" confirms that the Gaza Health Ministry reports the toll has risen to approximately 69,000-69,187 by mid-November 2025, as cited in multiple sources including WAFA (November 13, 2025: 69,187), PBS (November 8, 2025: 69,169), and Politico (November 8, 2025: tops 69,000). These figures align with the ongoing reporting methodology from the Hamas-controlled Gaza Health Ministry, consistent with the article's existing qualifiers (includes combatants, lacks independent verification, encompasses indirect causes). Updating the figure improves factual accuracy by reflecting the latest reported data without altering the neutral tone or sourcing caveats. The change should specify ""over 69,000 reported Palestinian deaths by November 2025"" while retaining the original phrasing about the source and limitations to maintain encyclopedic neutrality. No concerns about bias introduction, as the update is proportional and evidence-based; mainstream media sources were used sparingly here solely to report the raw ministry figure, hedged by the article's established skepticism."
10142,"Israel existed long before that, it existed in ancient times, got taken over by the ottoman empire, then got re-established in the 40s.",Israel was founded on 14 May 1948 through the Declaration of Independence.,"The edit suggestion seeks to add historical context to the sentence on Israel's founding, emphasizing ancient existence, Ottoman rule, and re-establishment in the 1940s rather than portraying 1948 as the initial founding. This categorizes as adding content for deeper historical accuracy.\n\n Research via web searches confirmed: Ancient kingdoms of Israel and Judah existed from around the Iron Age (e.g., sources like historical overviews from LiveScience and books on Israelite history). Palestine, including the region of ancient Israel, was under Ottoman control from the 16th century until World War I (e.g., UN history, Britannica, and Ottoman administrative records). The modern State of Israel in 1948 is frequently described as a re-establishment or restoration of Jewish sovereignty after nearly 2,000 years, supported by Israel's Ministry of Foreign Affairs (""Jewish independence was restored""), the Declaration of Independence referencing ancient promises, and multiple historical analyses (e.g., ICEJ, Jewish Virtual Library).\n\n These claims align with primary and authoritative sources, improving the article's precision by acknowledging continuity between ancient Jewish presence and the modern state, without contradicting the 1948 founding date. The addition fits encyclopedically in the introduction, enhancing neutrality by grounding in verified history rather than implying creation ex nihilo. No bias introduced, as the article already recognizes Israel as the Jewish nation-state and ancestral lands. Specific changes: Revise the highlighted sentence to incorporate ""re-established"" with brief ancient/Ottoman context, e.g., ""The modern State of Israel was re-established on 14 May 1948 through the Declaration of Independence, reviving Jewish sovereignty in the land of ancient Israel, which had been under Ottoman rule until the early 20th century."" This maintains focus and sourcing standards."
10143,"Wrong brackets, use () instead of []",[established under a British mandate from the League of Nations following the collapse of the Ottoman Empire],"The edit suggestion proposes changing square brackets [] to parentheses () around the explanatory phrase ""established under a British mandate from the League of Nations following the collapse of the Ottoman Empire."" This is a formatting adjustment for an aside or parenthetical remark. In encyclopedic and standard writing styles, parentheses are conventionally used for non-essential explanatory information to improve readability, while square brackets are typically reserved for editorial notes or citations. The article's citation format uses Markdown links `[](url)`, so square brackets here could potentially cause minor confusion, though not a rendering error. No factual changes are involved, and the edit enhances clarity without altering meaning or introducing bias. No research or search was necessary, as this qualifies as an obvious formatting fix under the guidelines, which strongly favor acceptance for such improvements that do not affect content. The specific change is to replace the square brackets with parentheses in the highlighted section."
10144,"You don't need a new sentence for Palestine, stick that sentence between brackets so you only mention Palestine once",partition of Mandatory Palestine into Jewish and Arab states. Mandatory Palestine had been established under a British mandate from the League of Nations following the collapse of the Ottoman Empire. Israel emerged as a refuge and homeland for Jews amid post-Holocaust displacement and historical persecution.[,"The edit suggestion focuses on restructuring sentences to eliminate redundancy in mentioning ""Mandatory Palestine"" twice in quick succession, by integrating the explanatory sentence (about its establishment under British mandate) into brackets or inline for conciseness, ensuring it is referenced only once explicitly. This is a stylistic improvement that enhances readability and flow without altering any facts, sources, or meaning. No research was needed, as the proposal does not involve factual claims, additions, or removals—only minor rephrasing for efficiency, which aligns with formatting fix criteria favoring acceptance for obvious readability enhancements. The original text's accuracy on Mandatory Palestine's history is preserved, as confirmed by the existing citations in the article (e.g., UN and historical sources). Specific change: Revise the relevant sentences to something like: ""which proposed the partition of Mandatory Palestine [established under a British mandate from the League of Nations following the collapse of the Ottoman Empire] into Jewish and Arab states."" This maintains encyclopedic tone and neutrality."
10145,"This doesn't read well and could be more factually detailed, reformat this paragraph to have more detail and grammatical sense.","Founded on 14 May 1948 through the Declaration of Independence, which followed the United Nations General Assembly's adoption of Resolution 181 on 29 November 1947 proposing the partition of Mandatory Palestine—established following the collapse of the Ottoman Empire under a British mandate from the League of Nations—into Jewish and Arab states, Israel emerged as a refuge and homeland for Jews amid post-Holocaust displacement and historical persecution.[4][5","The edit suggestion focuses on improving readability and grammatical structure of a complex, run-on sentence in the introduction, while also proposing to add more factual detail. No new factual claims are introduced in the suggestion itself, so no verification of novel content is required. The current text is factually accurate based on standard historical accounts of Israel's founding (UN Resolution 181 on November 29, 1947, Declaration of Independence on May 14, 1948, context of Mandatory Palestine post-Ottoman Empire), and restructuring for clarity would enhance encyclopedic tone without altering meaning or neutrality. However, the call to add ""more detail"" is vague and unspecified, risking unverified or biased expansions in a politically sensitive topic; thus, only the reformatting for better flow and grammar should be incorporated, such as breaking the long sentence into shorter ones or using clearer phrasing while preserving existing facts and sourcing. No search was needed as the suggestion does not propose specific factual changes, and the original content aligns with authoritative historical outlines. Concerns: Avoid adding details without sources to maintain neutrality; reject any unproposed expansions."
10148,"Might want to add that mandatory Palestine came as a result of the collapsing ottoman empire and a British mandate, because this sentence reads like it implies historical Palestine.",Mandatory Palestine into Jewish and Arab states,"Researched the origin of Mandatory Palestine using web search with query ""origin of Mandatory Palestine"". Multiple authoritative sources confirm that Mandatory Palestine was established following the collapse of the Ottoman Empire after World War I, with Britain receiving the mandate from the League of Nations in 1920 (effective 1923), as detailed in results from the United Nations (un.org/unispal/history/), Britannica, and historical encyclopedias like 1914-1918-online.net. These sources describe it as an administrative territory from former Ottoman lands under British control, not a continuation of an ancient ""historical Palestine"" entity. The suggestion adds precise, verified historical context to the partition reference, improving clarity and accuracy by distinguishing the modern mandate from broader historical connotations, without introducing bias or opinion. This fits naturally in the introductory sentence on the UN partition, enhancing encyclopedic neutrality and factual depth for readers unfamiliar with the term. No concerns with sourcing or relevance; the addition is proportional and directly addresses the highlighted text."
10149,"Not just their refuge, their homeland too",Israel emerged as a refuge,"The edit suggestion seeks to expand the phrase ""Israel emerged as a refuge"" to also recognize it as the homeland of the Jewish people, addressing a potential incompleteness in framing the state's founding solely around post-Holocaust refuge rather than the broader historical and national context. Research via web searches for ""Israel as historical homeland of Jewish people"" and ""Zionism Jewish homeland"" yielded consistent confirmation from authoritative sources, including Britannica (Zionism as establishing a Jewish state in the ancient homeland), ADL (Zionism for self-determination in ancestral homeland), AJC (ancestral connection spanning centuries), and Hoover Institution (Jewish indigeneity in the land). Browsing the Knesset page (https://knesset.gov.il/constitution/ConstMJewishState.htm) affirmed Israel's legal and declarative status as the Jewish state, with the Declaration of Independence establishing it as such and the Law of Return promoting Jewish immigration to the homeland. These sources verify the claim as factual and notable, rooted in historical, legal, and ideological foundations predating the Holocaust. The addition improves accuracy by balancing the refuge narrative with the established homeland dimension, already implied elsewhere in the article (e.g., ""nation-state of the Jewish people""), without introducing bias or opinion. It fits naturally in the introductory sentence on founding, enhancing encyclopedic completeness. No concerns about sourcing, as the edit aligns with primary references; accept by incorporating wording like ""a refuge and homeland"" to reflect this verified dual aspect."
10150,Known to jews/israel as Judea and Samaria,the West Bank and Gaza Strip,"Web searches confirmed that the Israeli government and many Israelis refer to the West Bank as Judea and Samaria, drawing from biblical regions. Key sources include a Knesset press release (February 2025) on legislation to replace ""West Bank"" with ""Judea and Samaria"" in official texts, Britannica's explanation that the term is used by the Israeli government for the West Bank, and discussions of its common usage in Hebrew. No sources contradicted this; it aligns with Israel's official terminology for the area. The edit adds factual, relevant information about nomenclature in the context of an article on Israel, enhancing completeness and neutrality by acknowledging the perspective of the subject without altering the internationally standard ""West Bank"" term or introducing bias. The suggestion applies primarily to the West Bank (Gaza Strip lacks a comparable alternative name), so incorporate by adding a parenthetical note, e.g., ""the West Bank (known in Israel as Judea and Samaria) and Gaza Strip."" This fits encyclopedic style for disputed names and improves the article without disruption."
10151,"This paragraph doesn't read well, refractor it","Israel is a sovereign parliamentary democracy in the Levant region of Western Asia, situated on the southeastern shore of the Mediterranean Sea in the historical birthplace of Christianity[1], and recognized internationally as the nation-state of the Jewish people.[2][3]","The edit suggestion proposes refactoring the highlighted introductory sentence for better readability, without altering facts, sources, or meaning. The current sentence is grammatically correct but lengthy, connecting multiple descriptive elements (government type, region, geography, historical significance, and national identity) in a single clause, which could benefit from minor rephrasing to improve flow while preserving encyclopedic tone and neutrality. No factual claims are modified, so no research or verification via search tools was necessary. Guidelines strongly favor acceptance for improvements in readability that do not change facts, and this aligns with formatting/structural enhancements for clarity. The suggestion is substantive as it targets a specific readability issue in the intro without introducing bias, additions, or removals. Accepting allows for a neutral refactor, such as breaking into shorter clauses or adjusting punctuation, ensuring the output remains accurate and sourced as is. No concerns with sourcing, as citations remain unchanged. Specific changes: Rephrase the sentence to enhance flow, e.g., separating geographical and historical descriptors if needed, while retaining all original content and links."
10153,"Also update that it is the birthplace of Christianity, quite important and should be in the first paragraph",as the nation-state of the Jewish people.[1][2],"Researched the geographical origins of Christianity using web searches for ""birthplace of Christianity"" and ""where did Christianity originate geographically."" Multiple sources, including Britannica, Christianity.com, HotBot, and Khan Academy, confirm Christianity originated in the 1st century CE in the Roman province of Judea, encompassing key sites like Jerusalem, Galilee, Nazareth, and Bethlehem—regions corresponding to modern-day Israel and adjacent Palestinian territories. While precise borders differ, authoritative references describe the area as the historical birthplace, aligning with the land's significance for Israel's article. No mainstream media was relied upon for the core fact; preference given to encyclopedic and educational sites. The addition is factual, notable, and encyclopedic, enhancing the introduction's context on the region's historical and cultural importance without introducing bias or opinion. It fits naturally near the highlighted text, e.g., expanding to note the land's role beyond the Jewish nation-state. Verified accuracy supports improvement in comprehensiveness; no concerns with sourcing as the claim holds under primary historical consensus. Specific change: Incorporate phrasing like ""and the birthplace of Christianity"" adjacent to the existing description of Israel as the nation-state of the Jewish people, ensuring neutrality and flow."
10160,"Hamas' attack on Oct 7th 2023 led to Israel's longest defensive war, lasting two full years and change. It was no low-level conflict and it deserves to be listed here.","7, and 1973, as well","The edit suggestion proposes adding the 2023–2025 Israel-Hamas war to the list of major defensive wars in the introduction, arguing it is Israel's longest defensive war and not a low-intensity conflict. Verification confirms the war began on October 7, 2023, and as of November 2025, it has lasted over two years with ongoing operations, including ground invasions and significant casualties, qualifying it as a full-scale conflict rather than low-intensity (e.g., [web:19], [web:20], [web:21]). It is described as a war involving large-scale military engagement, not merely persistent skirmishes. However, the suggestion's phrasing (""longest defensive war,"" ""no low-level conflict"") introduces subjective framing that could compromise neutrality. The introduction already covers the war extensively in later sections, but omitting it from the list of major wars understates its scale compared to 1948, 1967, and 1973. Partially incorporating a neutral mention improves accuracy and completeness without adopting the loaded terminology, ensuring the article remains encyclopedic and sourced via existing references to the event."
10161,"This source is clearly biased with a strong antisemtic/ anti israel bias.\nIt refers to 'Historic Palestine' which has never existed, the preceding polity to the foundation of Israel was the british mandate - which was granted at the san remo conference for the purpose ""of the establishment in Palestine of a national home for the Jewish people""\n\nThis sentence also omits what percentage of the territory in question was owned by local arab residents, and what was the percentage of land that was settled by Jews vs arabs",The plan allocated approximately 55% of the territory to the Jewish state despite Jews comprising about one-third of the population and owning around 7% of the land.[54],"The highlighted sentence accurately states the allocation (55-56%), population share (~33%), and Jewish private land ownership (~7%), as confirmed across multiple sources including analyses of UN Resolution 181. However, it omits key context: the British Mandate for Palestine, established at the 1920 San Remo Conference incorporating the Balfour Declaration, explicitly aimed at facilitating a Jewish national home, with much of the territory (~70-80%) being state or uncultivable land not privately owned by Arabs (Arab private ownership ~25-45% varying by source, but majority state domain). The ""despite"" phrasing risks implying inequity without noting the Mandate's purpose or that the Jewish allocation included the largely uninhabited Negev (~60% of Jewish area) for state viability. Incorporating context on Mandate intent and land status (state vs. private) enhances neutrality and accuracy without endorsing the suggestion's unverified bias claim against the unnamed source or ""Historic Palestine"" reference (absent in highlighted text). Sources: San Remo confirmed Jewish national home [web:21]; land ownership Jews ~6-7%, state majority [web:5][web:10][web:18]; allocation incl. desert [web:4]."

In [41]:
edit_df.reviewedBy.value_counts()[:50]

reviewedBy
               10109
ai-pipeline     1167
Name: count, dtype: int64